-- MySQL Script generated by MySQL Workbench
-- Sat May  2 13:32:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`master_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`master_countries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `verified` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`master_states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`master_states` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `verified` TINYINT(1) NULL DEFAULT '0',
  `master_country_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `master_country_id` (`master_country_id` ASC) VISIBLE,
  CONSTRAINT `master_states_ibfk_1`
    FOREIGN KEY (`master_country_id`)
    REFERENCES `mydb`.`master_countries` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`master_cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`master_cities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `verified` TINYINT(1) NULL DEFAULT '0',
  `master_state_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `master_state_id` (`master_state_id` ASC) VISIBLE,
  CONSTRAINT `master_cities_ibfk_1`
    FOREIGN KEY (`master_state_id`)
    REFERENCES `mydb`.`master_states` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `pincode` INT(6) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `google_map_latitude` FLOAT NULL DEFAULT NULL,
  `google_map_longitude` FLOAT NULL DEFAULT NULL,
  `master_city_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `master_city_id` (`master_city_id` ASC) ,
  CONSTRAINT `locations_ibfk_1`
    FOREIGN KEY (`master_city_id`)
    REFERENCES `mydb`.`master_cities` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`master_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`master_categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `verified` TINYINT(1) NULL DEFAULT '0',
  `parent_id` INT(11) NULL DEFAULT NULL,
  `typeLevel` INT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC) ,
  CONSTRAINT `master_categories_ibfk_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`master_categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`media_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media_details` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('photo', 'video', 'audio', 'document') NOT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `content` BLOB NULL DEFAULT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `mobile` VARCHAR(12) NULL DEFAULT NULL,
  `gender` ENUM('male', 'female', 'gay') NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `account_status` ENUM('active', 'inactive', 'block', 'disable') NOT NULL DEFAULT 'active',
  `password` VARCHAR(255) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profiles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `bio_title` VARCHAR(255) NULL DEFAULT NULL,
  `bio_description` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive', 'blocked', 'cancelled') NULL DEFAULT 'active',
  `profile_picture_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `profile_picture_id` (`profile_picture_id` ASC) ,
  INDEX `fk_profiles_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `profiles_ibfk_1`
    FOREIGN KEY (`profile_picture_id`)
    REFERENCES `mydb`.`media_details` (`id`),
  CONSTRAINT `fk_profiles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`schemaversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schemaversion` (
  `version` BIGINT(20) NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `md5` TEXT NULL DEFAULT NULL,
  `run_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.` profiles_to_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` profiles_to_categories` (
  `id` INT(11) NOT NULL,
  `profile_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC) ,
  INDEX `users_to_categories_ibfk_1_idx` (`profile_id` ASC) ,
  CONSTRAINT `users_to_categories_ibfk_1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `mydb`.`profiles` (`id`),
  CONSTRAINT `users_to_categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`master_categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
